### ISSUE TITLE
V-Rising Failed to load dll errors.

### ISSUE THREAD

**Issue by ad3d0** [gameserverapp/Platform#443] opened 2023-05-20 13:53 UTC
**On the Dediconnect (Windows Server 2019) when running V-Rising server trough GSA server log shows an unable to load DLL error.**

**Log starts with:**
`Plugins: Failed to load 'C:/serverfiles/VRisingServer_Data/Plugins\x86_64/BacktraceCrashpadWindows.dll' because one or more of its dependencies could not be loaded.`
**Then somewhere in the middle another alert:**
`System.DllNotFoundException: Unable to load DLL 'BacktraceCrashpadWindows': The specified module could not be found.`

**But if you try to run server from same directory manually via startup bat logs are clean of any errors. This happens even to a just created server.
I'm not sure how important that dll is, and what exactly that error affects. In both cases server seems to be running fine. But I've thought it still would be at least worth mentioning.**

**Comment by LuxPoseidon** [comment] 2023-05-21 22:53
This also seems to coincide with,
"Microsoft Media Foundation video decoding to texture disabled: graphics device is Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported for hardware-accelerated video decoding."

Upon some research this seems to be an issue if the server is being launched directly through its exe vs the bat file they provide.

**Comment by mvaessen** [comment] 2023-05-22 09:53
Hi,

Thanks for reporting!

During my recent tests I noticed those error logs too, but as far as I can tell are there no negative side effects. So for now I will close this issue since there doesn't seem to be any issues caused by it.

If you do come across any issues related to these logs, feel free to reach out again.

**Closed by mvaessen** 2023-05-22 09:53 UTC
