### ISSUE TITLE
Permission Issue adding game server to Dedihosted Cluster

### ISSUE THREAD

**Issue by Eurymachus** [gameserverapp/Platform#242] opened 2022-07-28 20:59 UTC
I have created an Admin Team called 'ARK Cluster Admins' with the relevant access permission for the cluster, the hosted server and configs.

When attempting to add a game server via the Game Servers - Cluster page it shows a permission error.
When attempting to add a game server via the Machines page no error is shown and the process continues as normal.
If a server is added via the Machines page under the action menu the created server does not inherit creator permissions and is not visible unless manually added under the team.

Steps to reproduce the behaviour:
1. Go to Game Servers as 'ARK Cluster' admin
2. Click on Add game server
3. See error

**Expected behaviour**
When adding a game server via the cluster section it should bring up the server configuration page, like it does when using the 'machines' page.

When adding a server via the machines page the server created should inherit a set of base permissions. Perhaps there could be a 'default permissions' on created servers?

**Screenshots**
![image](https://user-images.githubusercontent.com/1562316/181633563-ff357d2f-97b8-434e-9b0b-6bb564add9df.png)
![image](https://user-images.githubusercontent.com/1562316/181633602-add9824e-c467-46c7-8c1f-aaa5854f2b78.png)

**Comment by mvaessen** [comment] 2022-07-29 12:41
Thanks for reporting.

Reading the issue I see it involves 2 separate issues. The issue with `When adding a server via the machines page the server created should inherit a set of base permissions` is by design. If you want your admins to have access to all servers automatically you must give them full game server access. Or manually grant access when a new server was added. 

See alert from DediConnect "add game server" page 
<img width="968" alt="Screenshot 2022-07-29 at 14 40 36" src="https://user-images.githubusercontent.com/13402423/181762454-1d7b3755-ef4b-475a-8781-75dd7bc7eaf6.png">


The other issue you reported should be fixed now. Please reopen the issue if the problem still exists.

**Closed by mvaessen** 2022-07-29 12:41 UTC
Labels: status: ready for live
