### ISSUE TITLE
Teleport function ( GSA report system)

### ISSUE THREAD

**Issue by brothasx** [gameserverapp/Platform#583] opened 2023-11-25 11:08 UTC
When someone create a report and you check it out on GSA,
And you copy the teleport position command, it teleports you to the 50-50 coords instead of the exact location where te report has been made. 

**To Reproduce**
1. Create report ingame
2. Copy the teleport link trough GSA
3. Paste in console and apply
4. Results in 50-50 coords. 

![Screenshot_5](https://github.com/gameserverapp/Platform/assets/49365370/60a7f0a1-ab6e-4417-abc5-b6db909d1cea)
![Screenshot_4](https://github.com/gameserverapp/Platform/assets/49365370/30d4ffb6-fc77-414e-bd1e-877892d997fd)

**Comment by mvaessen** [comment] 2023-11-27 11:20
looking at the teleport command, it seems to have `X_` & `Y_` prefixed to the coordinates.
I cant reproduce this issue with the current latest test version of the mod, so it might be fixed on the next release. If it does, please close this ticket or post a reply! :)

**Comment by mvaessen** [comment] 2023-11-28 13:04
The new mod update is released, can you try this again to see if its fixed now?

**Closed** 2023-11-29 10:10 UTC
Labels: status: to be tested
