### ISSUE TITLE
Sub Packs/Shop Packs arrangement is mixed

### ISSUE THREAD

**Issue by CKScarpetti** [gameserverapp/Platform#754] opened 2024-02-02 11:17 UTC
The ShopPacks are always mixed up wildly after you save the page and then reload it or reopen the page.
Although everything has been arranged alphabetically.

The arrangement is also not correct if you want to send a packet to a player via the dashboard. The arrangement there will not be over. 
(Bild 1, Packages are actually arranged at the bottom and not in the middle.)
![Screenshot_20240202_121453_Chrome](https://github.com/gameserverapp/Platform/assets/47497723/5f9aeb76-025b-4d63-a98c-1401f3be0e4b)

In addition, when selecting the package to send, the cloned name of the package is displayed but not the new one.
(Bild 2, Package Name shows Clone Name not the new name.)
![Screenshot_20240202_121352_Chrome](https://github.com/gameserverapp/Platform/assets/47497723/b90303be-888b-4e2c-80c7-19f2d1733e62)

**Comment by mvaessen** [comment] 2024-02-05 13:36
Hi, i'm trying to reproduce the issue, but i can't.

Can you provide steps how to reproduce the issue? Like: go to x, then do Y, then see Z.

**Comment by CKScarpetti** [comment] 2024-02-05 14:08
What exactly do you mean, I should describe how the problems arise?



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Max Vaessen ***@***.***>
Datum: 05.02.24 14:37 (GMT+01:00)
An: gameserverapp/Platform ***@***.***>
Cc: CKScarpetti ***@***.***>, Author ***@***.***>
Betreff: Re: [gameserverapp/Platform] Sub Packs/Shop Packs arrangement is mixed (Issue #754)


Hi, i'm trying to reproduce the issue, but i can't.

Can you provide steps how to reproduce the issue? Like: go to x, then do Y, then see Z.

**Comment by CKScarpetti** [comment] 2024-02-05 15:49
Okay, I'll try to describe it better.

Problem 1:
For example, I sort the subpacks in the “Franky's Saddle BP” shop package alphabetically and save it.
Then I didn't use it for a few days and wanted to add another BP in this package. Afterwards, the sub-packages in this package were mixed up again, as if I had never sorted it.

Issue 2:
I have sorted all the packages under ShopPacks so that the things that are not displayed in the shop can be understood. That's how it's sorted...
But every time I want to credit a player with a specific pack using Send Deliveries, they are not sorted the way I have them sorted on the ShopPack page. These are then simply displayed somewhere in the list.

Problem 3:
For example, I cloned the packs for the boosters in the shop and then renamed them.
(Because it's quicker to replace a single line than to do the whole thing again.)
Under Shoppacks there are also the new names that I set, but when I go back to Player “Send Deliveries” it says, for example, XP Booster (Clone) (Clone) instead of XP Booster Svartalfheim



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Max Vaessen ***@***.***>
Datum: 05.02.24 15:10 (GMT+01:00)
An: gameserverapp/Platform ***@***.***>
Cc: CKScarpetti ***@***.***>, Author ***@***.***>
Betreff: Re: [gameserverapp/Platform] Sub Packs/Shop Packs arrangement is mixed (Issue #754)


I am trying to recreate the problems you describe, but i cannot recreate the problem. So i need a bit more info about where and how you do things so i can understand how you navigate the platform.

**Comment by mvaessen** [comment] 2024-02-05 15:55
Hi, 

Here are the steps I took to try reproduce the issues you reported:
- I created a new `collection` shop pack
- i added 3 sub packages (see image)
- i re-arranged them
- i reload the page
- all packages are in the exact place as i re-arranged them

![Screenshot 2024-02-05 at 16 53 33](https://github.com/gameserverapp/Platform/assets/13402423/1e0e483f-8d4e-4a05-9abb-4275e873d1ea)

I can not reproduce the issues you describe

**Comment by mvaessen** [comment] 2024-02-05 16:05
I was able to confirm that the `Send delivery`  (Deliveries -> Send delivery button) is not following the configured sort order. But the other issues I cannot reproduce.

**Comment by CKScarpetti** [comment] 2024-02-05 17:37
Strange, this has probably happened to me 3 times now.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Max Vaessen ***@***.***>
Datum: 05.02.24 16:55 (GMT+01:00)
An: gameserverapp/Platform ***@***.***>
Cc: CKScarpetti ***@***.***>, Author ***@***.***>
Betreff: Re: [gameserverapp/Platform] Sub Packs/Shop Packs arrangement is mixed (Issue #754)


Hi,

Here are the steps I took to try reproduce the issues you reported:

  *   I created a new collection shop pack
  *   i added 3 sub packages (see image)
  *   i re-arranged them
  *   i reload the page
  *   all packages are in the exact place as i re-arranged them

Screenshot.2024-02-05.at.16.53.33.png (view on web)<https://github.com/gameserverapp/Platform/assets/13402423/1e0e483f-8d4e-4a05-9abb-4275e873d1ea>

I can not reproduce the issues you describe

**Comment by mvaessen** [comment] 2024-02-05 18:23
any chance someone else (another admin) might have changed it?
Another thing that can happen, is when you have multiple tabs open. When you change the sort order on one tab, and switch to the other and save the page there, it might mess up the sortation.

**Comment by CKScarpetti** [comment] 2024-02-05 18:39
No, the admins only have access to the players and the reports, so they cannot simply change anything in the shop.

If it happens again I'll just let you know. 😅 Took photos this time.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Max Vaessen ***@***.***>
Datum: 05.02.24 19:23 (GMT+01:00)
An: gameserverapp/Platform ***@***.***>
Cc: CKScarpetti ***@***.***>, Author ***@***.***>
Betreff: Re: [gameserverapp/Platform] Sub Packs/Shop Packs arrangement is mixed (Issue #754)


any chance someone else (another admin) might have changed it?
Another thing that can happen, is when you have multiple tabs open. When you change the sort order on one tab, and switch to the other and save the page there, it might mess up the sortation.

**Comment by mvaessen** [comment] 2024-02-05 18:50
Sounds good! The issue with the `Send delivery` will be fixed in the next release 👍

**Comment by CKScarpetti** [comment] 2024-02-06 08:59
Yep, it's correct now, thanks for that.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Max Vaessen ***@***.***>
Datum: 05.02.24 20:59 (GMT+01:00)
An: gameserverapp/Platform ***@***.***>
Cc: CKScarpetti ***@***.***>, Author ***@***.***>
Betreff: Re: [gameserverapp/Platform] Sub Packs/Shop Packs arrangement is mixed (Issue #754)


The send delivery order should now be the same as on the shop pack page

**Closed** 2024-02-06 09:17 UTC
Labels: status: to be tested
