### ISSUE TITLE
ASA: Mods/Plugins Browser showing duplicate mod

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#664] opened 2023-12-18 15:29 UTC
**Describe the bug**
ARK: Survival Ascended
- When searching for "Homedeco" in the mod browser, 2 options show up (screenshot below).
- Both links point to the same item on CurseForge
- Both items have different version numbers

**To Reproduce**
- Under a gameserver, go to the mods/plugins tab
- Hit browse mods / plugins
- Search "Homedeco"

**Expected behavior**
I assume this should only show one result rather than two.

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/34605635/d7b49ba2-4caf-435b-8bb8-500660b686e9)
![image](https://github.com/gameserverapp/Platform/assets/34605635/ce667dc6-3dda-4402-8129-213f684d8c3b)
- Mouseover on the most recent file shows the first option version number (4945661 - left side) on the first screenshot (thanks Birdman)

**Comment by mvaessen** [comment] 2023-12-19 12:37
Looking at the curseforge api results it suggests this is something caused by changes being made to mods on the curseforge end of things. All mod ID's in the database are actual mod ID's, but it seems folks are abusing CF's upload system a bit

I'll see if we can have GSA update existing mods when the author or CF removes them 
![Screenshot 2023-12-19 at 13 36 48](https://github.com/gameserverapp/Platform/assets/13402423/68fe4fc5-f8fa-47bf-95ec-9d903493ae45)

**Comment by mvaessen** [comment] 2023-12-19 17:28
This should be fixed now. GSA will now automatically check for deleted mods for CurseForge. Thanks for reporting!

**Closed by mvaessen** 2023-12-19 17:28 UTC
Labels: status: to be tested
