### ISSUE TITLE
Player Played X hours in Total delivering per character time not Player

### ISSUE THREAD

**Issue by JetJeager** [gameserverapp/Platform#826] opened 2024-04-17 13:37 UTC
__Please make sure to leave out any sensitive information__!

**Describe the bug**
I assume this automation is supposed to run only based on player hours not character hours. Some folks found out that by making new characters they can keep triggering this.

**Expected behavior**
run per player hours. 

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/152654934/3e0ad2fa-c55f-4549-a2b7-34f7644f23f5)

**Additional context**
Happening on all servers.

**Comment by JetJeager** [comment] 2024-04-18 14:33
Another SS for more context 
![image](https://github.com/gameserverapp/Platform/assets/152654934/28304f6e-b296-4519-983f-4cc3d52f7f17)

**Comment by mvaessen** [comment] 2024-04-18 14:35
Hi, thanks for the extra screenshot. It's most likely caused by a bug in the trigger. I recommend disabling it for now and wait for a fix to get pushed out. I can't provide an ETA atm

**Comment by mvaessen** [comment] 2024-07-03 13:32
I ran various tests and cant reproduce the issue, so it's possible that this has been fixed now. Would you mind try this again and let me know if this is still happening for you?

**Comment by JetJeager** [comment] 2024-07-03 13:42
Yeah we can try this again.

**Comment by mvaessen** [comment] 2024-07-10 12:57
Hi @JetJeager, is this issue still happening for you?

**Comment by JetJeager** [comment] 2024-07-10 13:06
Sorry max I’ve been swamped and haven’t had the chance to test. Can you
leave it open for a bit longer?

**Comment by JetJeager** [comment] 2024-07-10 23:32
Hi max. Confirmed this is still happening

**Comment by JetJeager** [comment] 2024-07-11 12:22
Hi max. Here is how the action is set up. i dont know how to recreate it.
its more random now. When i first made this it was doing it every time a
character was created vs looking at total hours.
 [image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mvaessen** [comment] 2024-09-19 10:24
Hi, going to close this one. Feel free to reopen with steps to reproduce if this issue is still happening

**Closed by mvaessen** 2024-09-19 10:24 UTC
