### ISSUE TITLE
Admin Team Role unable to see Groups

### ISSUE THREAD

**Issue by DieselEffect** [gameserverapp/Platform#405] opened 2023-04-06 19:51 UTC
__Please make sure to leave out any sensitive information__!

**Describe the bug**
[ARK] Admin Team role cannot see the Groups (tribes) list but can see Characters, despite having the applicable permissions.

**To Reproduce**
Give Admin Team role the permissions
Assign a person to that team role
Have them check the Groups tab
They see 0

**Expected behavior**
The expectation is that the role have access to this list.

**Screenshots**
None

**Additional context**
None

**Comment by mvaessen** [comment] 2023-04-07 15:08
Hi, i tried reproducing but i can't see any issues.

Could you please provide more information? Like what game, screenshots showing what is missing etc etc

**Comment by mvaessen** [comment] 2023-04-26 11:01
Closed the issue due to lack of info

**Comment by DieselEffect** [comment] 2024-02-23 12:05
Sorry for this getting lost.

![image](https://github.com/gameserverapp/Platform/assets/34605635/f7c1b3f7-272e-4443-86d7-177ea9d6c085)
![image](https://github.com/gameserverapp/Platform/assets/34605635/30904c57-69a2-41ee-9e2a-d9638198c37c)

These are the permissions my particular admin team role has, however, they cannot see any Groups in the groups tab at all. It just shows nothing, even if I "view as role".
![image](https://github.com/gameserverapp/Platform/assets/34605635/04cafe10-f8d5-4b5b-b926-756ffdb3d0c7)

**Comment by mvaessen** [comment] 2024-02-27 17:36
@DieselEffect can you show how the permissions are configured for cluster & game servers?
Both cluster & game server permissions will affect what admins can see.

**Comment by DieselEffect** [comment] 2024-02-29 22:00
Yeah game servers are set to Full Access

**Comment by mvaessen** [comment] 2024-03-11 09:06
would you mind post a screenshot, so I can be certain there are no user errors involved?

**Comment by DieselEffect** [comment] 2024-03-14 15:01
![image](https://github.com/gameserverapp/Platform/assets/34605635/1e06545d-6799-4dbb-be55-2dfd03458bcd)
![image](https://github.com/gameserverapp/Platform/assets/34605635/40958de0-4e2f-4419-b19d-795f1ea7d27d)

**Comment by mvaessen** [comment] 2024-03-25 15:50
I'm testing this again, and again I cant reproduce any of the mentioned issues.

Your screenshots show that permissions were granted for a Palworld server, but there is no group support for this game. Could you please try replicate the issue with ARK? And in that case, please include screenshots showing the permissions for that particular server.

**Comment by DieselEffect** [comment] 2024-03-25 16:06
Here is a screenshot of the full settings for that Admin Team Role.

![image](https://github.com/gameserverapp/Platform/assets/34605635/8aa5330b-7254-4b86-acad-ad14a764d9be)

This is a screenshot of me looking at Groups when viewing Groups as that team.

![image](https://github.com/gameserverapp/Platform/assets/34605635/e61b3938-cb3c-4d9a-b707-9fc75f002ac9)

**Comment by mvaessen** [comment] 2024-03-25 16:36
Thanks for the extra info, I was able to reproduce the issue now. Should be fixed in the next deployment

**Closed** 2024-04-01 18:30 UTC
Labels: status: to be tested
