### ISSUE TITLE
Creating new Forum Category spits error

### ISSUE THREAD

**Issue by zerafox** [gameserverapp/Platform#786] opened 2024-02-29 13:23 UTC
__Please make sure to leave out any sensitive information__!

**Describe the bug**
Attempting to create a new Category section on website Forums spits out error 

**To Reproduce**
1. Go to Forum section of website
2. Click on Attempt to add/create New Category
3. Fill in information to create said New Category

**Expected behavior**
I expected a new Category to be created

**Screenshots**
https://gyazo.com/49c9f056caef0185aa1c50d76f88470e
https://gyazo.com/1f4d3d8045331ec54b1aab554e020cd8

**Comment by mvaessen** [comment] 2024-03-25 11:38
Hi,

I'm trying to reproduce the issue with the exact same information as provided, but I cant seem to reproduce the issue.
Can you show the settings for the parent category? Perhaps that will help me reproduce.

![Screenshot 2024-03-25 at 12 37 01](https://github.com/gameserverapp/Platform/assets/13402423/4218fb13-415a-4cfe-9d47-2c1e6908b846)
![Screenshot 2024-03-25 at 12 37 06](https://github.com/gameserverapp/Platform/assets/13402423/978cfd8f-adf7-4066-b39b-5ceac2434e46)

**Comment by zerafox** [comment] 2024-03-26 15:50
I don't know how to get that information for an existing/parent category?
Where do I find that?

I tried toggling "Enable Threads" to see if that was somehow preventing it, but no change.

**Comment by mvaessen** [comment] 2024-03-26 16:32
are you able to post the link to the specific forum section where you experienced the issue? That should help me recreate the scenario

**Comment by zerafox** [comment] 2024-03-26 23:09
https://iron-nexus.gameserverapp.net/forum/537-the-cave

**Comment by mvaessen** [comment] 2024-03-27 11:15
I tried a number of things, but im unable to reproduce the issue. 
Can you try recreate the category structure from the ground up, and see if it still happens? 

![Screenshot 2024-03-27 at 12 10 23](https://github.com/gameserverapp/Platform/assets/13402423/5e721046-c3e1-4df4-98f4-674b6327f427)
![Screenshot 2024-03-27 at 12 12 57](https://github.com/gameserverapp/Platform/assets/13402423/2b68b0cb-deb6-493c-b28a-59ce845faa72)
![Screenshot 2024-03-27 at 12 13 21](https://github.com/gameserverapp/Platform/assets/13402423/19b8680f-c717-4862-a0ea-d70b55685472)

**Comment by zerafox** [comment] 2024-03-27 12:10
I can't explain what's happening *shrug*
https://gyazo.com/270b3198c382c80c59e25fe43ea34140

But a brand new root category and attempting to create another category inside that one, I've made no changes, gives me the same error.
I can make a new root, but I cannot make a category within the new root "test1".

**Comment by mvaessen** [comment] 2024-03-27 12:53
Are you maybe able to screenrecord the steps you take? That should ensure I do exactly like you, which hopefully will help me reproduce the issue.

**Comment by birdman3131** [comment] 2024-03-27 14:07
I would also ask what browser and possibly what extensions you have. Or to try it on a different browser. Not saying that is it but its worth a glance.

**Comment by mvaessen** [comment] 2024-04-04 12:06
@zerafox is this still an ongoing issue? if so, please see above messages :)

**Comment by mvaessen** [comment] 2024-04-10 14:11
Closing due to lack of info

**Closed by mvaessen** 2024-04-10 14:11 UTC
Labels: status: needs more info

**Comment by zerafox** [comment] 2024-04-10 16:21
Sorry, I don't exactly have a way to record what exactly I'm doing afraid.
