### ISSUE TITLE
ASA: Console Players

### ISSUE THREAD

**Issue by GnarlyVR** [gameserverapp/Platform#650] opened 2023-12-15 02:57 UTC
With the new integration app update, my console players are reporting they are unable to use LB and right stick in for crouch.

**Comment by mvaessen** [comment] 2023-12-15 15:31
hi, are you 100% sure this is caused by the GSA mod? Did you rule out any chance that this is caused by another mod / a recent ARK update?

**Comment by DieselEffect** [comment] 2023-12-18 02:36
I have had over a hundred unique console players in the past 3 days and not one of them has reported this issue. They are most, if not all Xbox. I cannot speak for Playstation.

**Comment by Spencer021** [comment] 2023-12-18 06:43
This was due to a plugin, woolys shop/shopUI plugin. It should be fixed

**Comment by mvaessen** [comment] 2023-12-18 11:51
Going to close and assume it's some external issue

**Closed by mvaessen** 2023-12-18 11:51 UTC
Labels: status: needs more info
