### ISSUE TITLE
Automatic update for all players causes players to show up as being recently online

### ISSUE THREAD

**Issue by Brentacon** [gameserverapp/Platform#744] opened 2024-01-28 15:43 UTC
**Describe the bug**
I posted a screenshot, just wondering why this is happening? I use this daily to check who hasnt been online so I can wipe their bases seem the decay of ark is broken to hell, its literally showing me online but says I havnt been on for a week. cheers
![image](https://github.com/gameserverapp/Platform/assets/62757826/15991442-189a-4b16-acc4-04c005869415)

**Comment by mvaessen** [comment] 2024-01-28 15:48
For reference https://discord.com/channels/315049169071112193/1201176986542936134/1201176986542936134

**Comment by mvaessen** [comment] 2024-02-12 15:27
Upon further inspection is there no "re-index for all players" once per day anymore. So that can't be responsible for the status update.

People are reporting that the `last activity` at is not showing the right date. It's possible that this is caused by reconnecting players with tribes

**Comment by mvaessen** [comment] 2024-07-03 13:44
Based on the information I was able to retrieve from the code, is the group `last active` date updated when a player logs in. So most likely was this caused by people that are part of the tribe, loggin in. 

It's also possible that another character of that player logged in, and GSA was not yet aware of the new character on that server. In that case it might touch the `last activity` for the wrong tribe.

Im going to close this one for now, if the issue comes up again, please let me know

**Closed by mvaessen** 2024-07-03 13:44 UTC
