### ISSUE TITLE
ASA Shop : Filters : Incorrect amount in brackets

### ISSUE THREAD

**Issue by laurenskok** [gameserverapp/Platform#605] opened 2023-11-29 21:05 UTC
**Describe the bug**
The filters are showing the number of all shop packs under a tag. Regardless if they are activated or not. 

**To Reproduce**
1. Make sure you have several shop packs tagged with a tag (for example 'weapons')
2. Activate 1 shop pack, and have the others disabled
3. If you go ingame, you will see that the number from the filters is counting everything (also the inactive packs)

**Expected behavior**
The filters are only counting the activated packs. 

**Screenshots**
![image](https://github.com/gameserverapp/Platform/assets/12686222/e14cb298-3e7c-4d46-9e47-62fadd876173)

**Comment by mvaessen** [comment] 2023-11-29 21:06
duplicate of #581

**Closed** 2023-11-29 21:06 UTC
